#!/bin/sh

set -e

if test $# -eq 1; then l=$1; else l='overhang traverse vertical'; fi

for i in $l
do ffmpeg -i data/$i/[A-Z]*.mp4 2>&1 | awk -F: '
sub(/.*Duration: /, "") && sub(/,.*/, "") {
    print "'$i'", 60 * $2 + $3
}
'
done
